services:
  # The container_name should preferably be the name of the project

  # Odoo container
  odoo-web:
    container_name: amyu16
    build:
      context: ./projects
      dockerfile: ./Dockerfile.amyu16
    volumes: # /mnt/extra-addons is required, see odoo documentation
    - odoo-web-data:/var/lib/odoo
    # Requirements
    - ./projects/amyu16/requirements.txt:/etc/odoo/requirements.txt
    # AMYU Systems
    - ./projects/amyu16/amyusys:/mnt/extra-addons/amyusys
    - ./projects/amyu16/amyu1:/mnt/extra-addons/amyu1
    - ./projects/amyu16/bcs:/mnt/extra-addons/bcs
    - ./projects/amyu16/ets:/mnt/extra-addons/ets
    - ./projects/amyu16/hrad:/mnt/extra-addons/hrad
    - ./projects/amyu16/tracker:/mnt/extra-addons/tracker
    # Common modules
    - ./projects/amyu16/common/auth_session_timeout:/mnt/extra-addons/auth_session_timeout
    - ./projects/amyu16/common/employee_documents_expiry:/mnt/extra-addons/employee_documents_expiry
    - ./projects/amyu16/common/hide_menu_user:/mnt/extra-addons/hide_menu_user
    - ./projects/amyu16/common/hr_organizational_chart:/mnt/extra-addons/hr_organizational_chart
    - ./projects/amyu16/common/mobile:/mnt/extra-addons/mobile
    - ./projects/amyu16/common/muk_web_theme:/mnt/extra-addons/muk_web_theme
    - ./projects/amyu16/common/onehr_fixed_assets:/mnt/extra-addons/onehr_fixed_assets
    - ./projects/amyu16/common/onehr_payroll:/mnt/extra-addons/onehr_payroll
    - ./projects/amyu16/common/onehr_tk:/mnt/extra-addons/onehr_tk
    - ./projects/amyu16/common/report_xlsx:/mnt/extra-addons/report_xlsx
    - ./projects/amyu16/common/prt_report_attachment_preview:/mnt/extra-addons/prt_report_attachment_preview
    ports:
    - "8069:8069"
    expose:
    - 8069
    environment:
    - HOST=odoo-db
    - USER=odoo
    - PASSWORD=admin

  
  # React container
  # react-web:
  #   container_name: animelist
  #   build:
  #     context: ./projects
  #     dockerfile: ./Dockerfile.animelist
  #   volumes:
  #     - ./projects/animelist:/react
  #   ports:
  #   - "3000:3000"
  #   expose:
  #   - 3000

  # Django container
  # django-web:
  #   container_name: amyu-lms-private
  #   build:
  #     context: ./projects
  #     dockerfile: ./Dockerfile.lms
  #   volumes:
  #     - ./projects/amyu-lms-private:/django
  #   ports:
  #   - "8000:8000"
  #   expose:
  #   - 8000
  
  # Database container
  odoo-db:
    container_name: odoo-db
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata


# NOTE: Uncomment external true if you are trying to **re-attach** the volumes to new docker compose
# The best way to do this so that your data is saved even when database container is deleted:
# - First, run "docker compose up" with the "external: true" commented out
# - Then, rerun "docker compose up" after uncommenting "external: true".
volumes:
  odoo-web-data:
    name: odoo-web-data
    external: true
  odoo-db-data:
    name: odoo-db-data
    external: true