version: '3.1'
services:
  # odoo web app
  odoo-web:
    container_name: odoo-web
    build:
      context: ./
      target: dev
    depends_on:
    - odoo-db
    volumes:
    # - odoo-web-data:/var/lib/odoo
    # - .:/workspace/amyu-ets-demo:cached
    - ./extra-addons:/mnt/extra-addons
    ports:
    - "8069:8069"
    expose:
    - 8069
    environment:
    - HOST=odoo-db
    - USER=odoo
    - PASSWORD=odoo

  # postgres db
  odoo-db:
    container_name: odoo-db
    image: postgres:15
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - odoo-db-data:/var/lib/postgresql/data/pgdata

# Uncomment external true if you are trying to re-attach the volumes to new docker compose
volumes:
  odoo-db-data:
    name: odoo-db-data
    external: true