FROM  python:latest

ENV PYTHONUNBUFFERED=1

WORKDIR /django
COPY <project_folder_name> /django/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY extra-files/django/entrypoint.sh /entrypoint/

EXPOSE 8000

ENTRYPOINT [ "/entrypoint/entrypoint.sh" ]