# ---------------------------- 
#      ReactJS Docker Image 
# ----------------------------

FROM node:latest

WORKDIR /react

COPY <project_folder_name>/package.json /react/
COPY <project_folder_name>/src /react/

RUN npm install

EXPOSE 3000

CMD ["npm", "start"]
